DROP TABLE users;
DROP TABLE locations;

CREATE TABLE IF NOT EXISTS users(
	username VARCHAR(25) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	password VARCHAR(25) NOT NULL,
	email VARCHAR(25),
	phone VARCHAR(25));
	
CREATE TABLE IF NOT EXISTS locations(
	id INT AUTO_INCREMENT PRIMARY KEY,
	latitude FLOAT NOT NULL, 
	longitude FLOAT NOT NULL,
	timestamp VARCHAR(25) NOT NULL,
	username VARCHAR(25) NOT NULL);
